name: OverlayFix
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      versionString:
        description: 'Version String'
        type: string
env:
  VCPKG_BINARY_SOURCES: clear
  BUILD_TYPE: Release
  PROJECT_NAME: OverlayFix
  PROJECT_LONG_NAME: SKEE64 Overlay Fix for Skyrim
jobs:
  build-skse:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Get CMake
        uses: lukka/get-cmake@v3.27.4
        with:
          cmakeVersion: "3.27.4"
      - name: vcpkg cache
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: "a4275b7eee79fb24ec2e135481ef5fce8b41c339"        
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          configurePreset: default
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE:STRING=C:/vcpkg/scripts/buildsystems/vcpkg.cmake']"
          buildPreset: release
          buildPresetAdditionalArgs: "['--config Release']"
      - name: Move binaries
        run: |
          cd ${{github.workspace}}/build/bin/release
          mkdir artifacts
          cd artifacts
          mkdir SKSE
          mkdir SKSE/Plugins
          move ../OverlayFix.dll SKSE/Plugins
          move ../OverlayFix.pdb SKSE/Plugins
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: OverlayFix
          path: build/bin/release/artifacts
          retention-days: 90
